/**
 * Centralized icon set.
 *
 * Re-exports Phosphor Icons under names matching the previous lucide-react
 * usage so existing call sites keep working. Pick from this file when adding
 * new icons so the dashboard stays visually consistent.
 */
export {
  Pulse as Activity,
  Warning as AlertCircle,
  Warning as AlertTriangle,
  Warning as TriangleAlert,
  List as AlignJustify,
  List,
  ArrowDown,
  ArrowDownRight,
  ArrowLineDown as ArrowDownToLine,
  ArrowLeft,
  ArrowsLeftRight as ArrowLeftRight,
  ArrowsLeftRight as ArrowRightLeft,
  ArrowUp,
  ArrowsDownUp as ArrowUpDown,
  ArrowLineUp as ArrowUpFromLine,
  ArrowUpRight,
  ChartBar as BarChart2,
  ChartBar as BarChart3,
  Bell,
  Bookmark,
  Robot as Bot,
  Calculator,
  Check,
  CheckCircle as CheckCircle2,
  CheckSquare,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  Clock,
  Clock as Clock3,
  Command,
  Copy,
  Crown,
  CurrencyDollar as DollarSign,
  Download,
  Drop as Droplets,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FileText,
  Funnel as Filter,
  Fish,
  Fire as Flame,
  Gift,
  GitDiff as GitCompareArrows,
  Globe,
  Hash,
  House as Home,
  Images,
  Info,
  Key as KeyRound,
  Stack as Layers,
  SquaresFour as LayoutDashboard,
  GridFour as LayoutGrid,
  Lightbulb,
  ChartLine as LineChart,
  Link as Link2,
  CircleNotch as Loader2,
  Lock,
  SignIn as LogIn,
  SignOut as LogOut,
  Medal,
  PencilSimple as Pencil,
  Percent,
  ChartPie as PieChart,
  ChartPie as PieChartIcon,
  Plus,
  Power,
  Power as PowerOff,
  ArrowsClockwise as RefreshCw,
  Rocket,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  Gear as Settings,
  Share as Share2,
  Shield,
  ShieldWarning as ShieldAlert,
  SlidersHorizontal,
  Sparkle as Sparkles,
  Star,
  Sun,
  Target,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Triangle,
  Trophy,
  User,
  UserMinus,
  UserPlus,
  Users,
  SpeakerHigh as Volume2,
  Wallet,
  Lightning as Zap,
  X,
} from "@phosphor-icons/react";
